/**
    This project has been generated by hxdiscord. This code was taken from the original GitHub repository.
    You can remove this comment since it's not necessary.
**/

import hxdiscord.DiscordClient;
import hxdiscord.utils.Intents;
import hxdiscord.types.*;
class Main
{
    static var Bot:DiscordClient;
    static function main()
    {
        Bot = new DiscordClient("your token here", [Intents.ALL], false);
        Bot.onReady = onReady;
        Bot.onMessageCreate = onMessageCreate;
    }

    public static function onReady()
    {
        trace("The bot is ready");
    }

    public static function onMessageCreate(m:Message)
    {
        if (m.content == "hi")
        {
            m.reply({content:"Hello!"}, true); //true or false, the bot will mention the user
        }
    }
}
                